### PR TITLE
#164829365 Implement Article Review 

### PR DESCRIPTION
**Pull request by MainaKamau92**
#### Description
The PR introduces the ability of an authenticated user to give a review of an article through writing a small description of the article and giving a rating from 1-5. It also gives the user the ability to edit or delete their review.

#### The working endpoints include:

|  Method  | Endpoint |  Description |
|---|---|---|
| GET  | /api/articles/{slug}/reviews/ | Get all reviews for an existing article |
| POST  | /api/articles/{slug}/reviews/:username | Create a new review for an existing article  |
| PUT  | /api/articles/{slug}/reviews/:username  | Edits an existing review  |
| DELETE  | /api/articles/{slug}/reviews/:username  | Deletes an existing review  |

#### Description of Task to be completed?
An authenticated user should be able to create, read, update and delete their review.
An authenticated user should not be able to review their own article.
An authenticated user should not be able to edit another user's reviews.
An authenticated user has the option of ignoring the review body and just give the numerical rate
Users that are not authenticated should not be able to access this service.

*NOTE*
Authenticating as a user requires you to use the sign-up and login views.

1) Sign-up
Access the endpoint using: http://127.0.0.1:8000/api/users/
Example sign-up payload:
```
{
  "user": {
    "email": "demo@mail.com",
    "username" :"Mary",
    "password":abc123ok
  }
}
```

2) Login
Access the endpoint using: http://127.0.0.1:8000/api/users/login/
Example login payload:
```
{
  "user": {
    "email": "demo@mail.com",
    "password":abc123ok
  }
}
```
After a successful login, a token will be returned. Copy and include it in the authorization headers when attempting to access the reviews view.

#### How should this be manually tested?
* Clone repo to local machine
* `cd` into cloned repository folder
* Create a virtual environment by running `virtualenv venv`
* Activate the virtualenv `source venv\bin\activate`
* Install dependencies `pip install -r dev-requirements.txt`
* Run the Django server to serve up the app `python manage.py runserver`

#### Create an article to review
Create an article (POST: localhost/api/articles/)
```
Request

{
    "article":
        {
            "title": "Test article title",
            "body": "Lorem ipsum dolor sit amet",
            "description": "Authors Haven Description Test article",
            "is_published": true
        }
}
```
```
Response

    "success": "Article 'Test article title' created successfully",
    "article": {
        "id": 1,
        "title": "Test article title",
        "body": "Lorem ipsum dolor sit amet",
        "description": "Authors Haven Description Test article",
        "is_published": true,
        "date_created": "2019-04-06T07:08:05.901158Z",
        "date_modified": "2019-04-06T07:08:05.901251Z",
        "slug": "authors-haven-test-four-74c2f6013c1c",
        "author": {
            "email": "test@gmail.com",
            "username": "tester"
        }
    }
}
```
#### Create a Review

* For **POST** endpoint
```
{
  "review": {
    "review_body":"I really liked the article",
	"rating_value": 5
  }
}

```
###### Expected Response
```
{
    "success": "Review for Authors Haven Test created successfully",
    "Review": {
        "id": 2,
        "rating_value": 5,
        "reviewer_username": "Mary",
        "article": 1,
        "review_body": "I really liked the article",
        "date_created": "2019-04-09T12:55:26.609680Z",
        "date_modified": "2019-04-09T12:55:26.609720Z",
        "reviewed_by": 1
    }
}
```

* For **PUT** endpoint
```
{
  "review": {
    "review_body":"I loved liked the article",
	"rating_value": 5
  }
}

```
###### Expected Response
```
{
    "message": "Review for 'authors-haven-test-4e9d087359c6' has been updated.",
    "Review": {
        "id": 2,
        "rating_value": 5,
        "reviewer_username": "Mary",
        "article": 1,
        "review_body": "I really loved the article",
        "date_created": "2019-04-09T12:55:26.609680Z",
        "date_modified": "2019-04-09T13:08:44.857633Z",
        "reviewed_by": 1
    }
}
```

#### How has this been tested?
- [x] Unittest
Run `python manage.py test` to run the test and receive a report with test coverage.

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/164829365

### CODE REVIEW

**Review by kihuha — DISMISSED** [review]
Works as described

**Comment by WNjihia** [comment]
@MainaKamau92 there are merge conflicts. Kindly resolve them

**Comment by MainaKamau92** [comment]
@WNjihia, Resolved.

**Review by kihuha — DISMISSED** [review]

**Review by Raywire — DISMISSED** [review]
Everything works well.

**Review by WNjihia — DISMISSED** [review]

**Comment by kihuha** [comment]
I think you can use a `try - catch` block to better handle this error. I was trying to send a PUT request without adding my username

Screenshot 2019-04-11 at 22 44 12

**Comment by kihuha** [comment]
Kindly update your PR's working endpoints clearly indicating where I need to append the username; as is required in the case of making a PUT request

**Review by Kyppy — DISMISSED** [review]
Good work overcoming the issue with the 'round' function. I would recommend that you add docstrings for all of your methods and classes, and to expound a bit more on the ones that you have written.

**Comment by WNjihia** [comment]
@MainaKamau92 there are merge conflicts on this pr. Kindly fix them

**Comment by MainaKamau92** [comment]
@WNjihia all conflicts have been resolved.

**Review by kirega — APPROVED** [review]
The code is neat and legible. Feedback has been implemented

**Review by kirega — DISMISSED** [review]

**Review by LarryKarani — DISMISSED** [review]
Tested it locally works fine

**Review by Raywire — DISMISSED** [review]
The functionality works well and the code quality is also good.

**Review by Kyppy — DISMISSED** [review]
It's good to remember to remove commented code. Nice additions to your test suite. The tests look thorough.

**Review by LarryKarani — DISMISSED** [review]
Everything looks fine after the merge conflicts fix

**Review by Raywire — DISMISSED** [review]
Works well good job on the coverage.

**Review by kihuha — DISMISSED** [review]

**Comment by kihuha** [comment]
Looks okay.

**Review by Raywire — DISMISSED** [review]
Works as expected.

**Review by WNjihia — DISMISSED** [review]

**Comment by WNjihia** [comment]
@MainaKamau92 there are a couple of conflicting files. Kindly look into this

**Review by Raywire — APPROVED** [review]

**Comment by MainaKamau92** [comment]
@WNjihia Resolved.

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
