### PR TITLE
 #164829374 Add articles pagination

### PR DESCRIPTION
**Pull request by LarryKarani**
__What does this PR do?__
Adds pagination to the articles.

__Description of the tasks to be completed__

Add functionality that returns at most ten articles per page.

__How should this be manually tested?__

- Clone the repo, and navigate to the root directory.
- Fetch all the branches and checkout into this feature's branch using the commands below
         -`git fetch --all`
         -`git checkout ft-pagination-articles-#164829374`

- Create a virtual environment and then activate the environment  as shown below
        - `virtualenv venv`
        - `source venv/bin/activate`

- Install all the required dependencies using pip by running
        - `pip install -r requirements.txt`
- Run the Django server to serve up the app by typing
        - `python manage.py runserver`

- Navigate to the endpoint shown below on postman
- Switch the pages by copy-pasting the next or the previous URL on the output data on postman
- The output should be a maximum of ten articles

Screenshot 2019-04-18 at 07 18 15

### CODE REVIEW

**Comment by kihuha** [comment]
How do you access the next or previous batch of articles? Please include this in your PR

I have updated the PR

**Comment by LarryKarani** [comment]
> How do you access the next or previous batch of articles? Please include this in your PR
> 
I have updated the PR

**Review by kihuha — DISMISSED** [review]
Works as described

**Comment by kihuha** [comment]
Ensure you update your branch

**Review by Raywire — APPROVED** [review]
I have tested it and I can be able to access the next page if items are more than 10 and I can be able to go to the previous page. I like how I can also be able to change the default number of items per page.
Screenshot 2019-04-18 at 12 09 05
Screenshot 2019-04-18 at 12 08 19
Screenshot 2019-04-18 at 12 07 20

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
