### PR TITLE
#164829382  Liking and Disliking comments 

### PR DESCRIPTION
**Pull request by kirega**
#### Description
This PR adds the feature that allows users to like or dislike an article
#### Type of change
This is feature is additive. It adds a like-dislike model to record the likes and dislikes of each user, views for user interaction, and tests.

Below are the various endpoints and the expected payloads.
#### Note:
To test this you will need to create at least one article and a comment for the same. 

Below is a guide on how to achieve this :
##### `POST: localhost/api/articles/`
- Create an article 
```
{
    "article":
        {
            "title": "Authors Haven Test Four",
            "body": "Lorem ipsum dolor sit amet",
            "description": "Authors Haven Description Four",
            "is_published": true
        }
}
````
##### `POST` `localhost/api/articles/<slug>/comments/`
-  the <slug> is the uinque identifier for the article. It  is  obtained  from the previous POST above.
- The POST here create a comment for the article

```
{
    "comment": 
        {
            "body": "Great article, I enjoyed the read"
        }  
}
```
##### `POST` `localhost/api/articles/comments/<pk>/like/`
-  To like a comment send the post request with an empty body
- the `<pk>` is the identifier for the specific comment we are liking, obtained from the response of the create comment step above
- Output is as follows:
image

##### `POST` `localhost/api/articles/comments/<pk>/dislike/`
-  To dislike a comment send the post request with an empty body 
_  Expected output is:
image

#### How Has This Been Tested?
- Clone the repo and navigate to the root directory
- Create a virtual environment by typing `virtualenv venv` and activate it
- Install requirements by typing `pip install -r dev-requirements.txt`
- Setup a database and ensure that your `.env` has the following variables:
```
export SECRET_KEY
export DEBUG
export DATABASE_URL
export SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
export SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
export SOCIAL_AUTH_TWITTER_KEY
export SOCIAL_AUTH_TWITTER_SECRET
export AH_HOST
export CLOUDINARY_NAME
export CLOUDINARY_API_KEY
export CLOUDINARY_API_SECRET
export SENDGRID_API_KEY
export FROM_EMAIL
export URL
export EMAIL_HOST=
export EMAIL_HOST_PASSWORD
export EMAIL_PORT
export EMAIL_USE_TLS
export DOMAIN

```
- Run the tests by typing `python manage.py test`

#### Checklist:
Delivers on this PT story  https://www.pivotaltracker.com/story/show/164829382

### CODE REVIEW

**Review by Raywire — DISMISSED** [review]
Works as it should.

**Review by kihuha — DISMISSED** [review]
Works as described

**Review by WNjihia — DISMISSED** [review]

**Review by LarryKarani — DISMISSED** [review]
I like the way you implemented the revert feature when a user likes or dislikes a comment twice. Good job.

**Review by Kyppy — DISMISSED** [review]
Your feature works well and delivers what is expected. Good job accounting for when a user likes/dislikes a feature twice.

**Review by LarryKarani — DISMISSED** [review]

**Review by Raywire — DISMISSED** [review]

**Review by kihuha — DISMISSED** [review]

**Review by LarryKarani — APPROVED** [review]

**Review by Kyppy — APPROVED** [review]

**Pull request merged**
