### PR TITLE
#164829364 Updates article payload for post and put endpoints 

### PR DESCRIPTION
**Pull request by Raywire**
**What does this PR do?**
Updates article payload for POST and PUT endpoints.

**Description of the task to be completed**

1. When a POST request to create a new article is made, the returned payload now contains the created article.

2. When a PUT request to update an article is made, the returned payload now contains the updated article.

3. The PUT request now allows a user to publish or unpublish an article by updating the 'is_published' field in the request payload.

4. Refactor to remove repetitive code.

**How should this be manually tested?**

- Once you clone the repo, open your terminal window and navigate to the root directory.
- Create a virtual environment and then activate the environment by as shown below
```python
virtualenv venv
source venv/bin/activate
```
- Install all the required dependencies using pip by running 
```python
pip install -r requirements.txt
```
- Run the Django server to serve up the app by typing 
```python
python manage.py runserver
```
- Using postman, send a request with the data described in the format below.

**Create an article (POST: localhost/api/articles/)**

**Request**
```json
{
    "article":
        {
            "title": "Authors Haven Test Four",
            "body": "Lorem ipsum dolor sit amet",
            "description": "Authors Haven Description Four",
            "is_published": true
        }
}
````

**Response**
```json
    "success": "Article 'Authors Haven Test Four' created successfully",
    "article": {
        "id": 70,
        "title": "Authors Haven Test Four",
        "body": "Lorem ipsum dolor sit amet",
        "description": "Authors Haven Description Four",
        "is_published": true,
        "date_created": "2019-04-06T07:08:05.901158Z",
        "date_modified": "2019-04-06T07:08:05.901251Z",
        "slug": "authors-haven-test-four-74c2f6013c1c",
        "author": {
            "email": "simiyuwire@gmail.com",
            "username": "raywire"
        }
    }
}
```
**Update an article (PUT: localhost/api/articles/authors-haven-test-four-74c2f6013c1c)**

**Request**
```json
{
    "article":
        {
            "title": "Authors Haven Test Updated",
            "body": "Updated lorem ipsum dolor sit amet",
            "is_published": false
        }
}
```

**Response**

```json
{
    "success": "Article 'Authors Haven Test Updated' updated successfully",
    "article": {
        "id": 70,
        "title": "Authors Haven Test Updated",
        "body": "Updated lorem ipsum dolor sit amet",
        "is_published": false,
        "date_created": "2019-04-05T17:49:58.442674Z",
        "date_modified": "2019-04-06T16:30:57.935046Z",
        "slug": "authors-haven-test-four-74c2f6013c1c",
        "author": {
            "email": "simiyuwire@gmail.com",
            "username": "raywire"
        }
    }
}
```

***Notes***
If the 'is_published' field is not specified in the POST request for creating an article, it defaults to false

**Relevant PT stories**
https://www.pivotaltracker.com/story/show/164829364

### CODE REVIEW

**Comment by kihuha** [comment]
Please change the title to conform to the Andela best practices manual

**Review by kirega — APPROVED** [review]

**Comment by MainaKamau92** [comment]
I noticed I can change the `is_published` field, isn't supposed to be read-only?

**Comment by Raywire** [comment]
> I noticed I can change the `is_published` field, isn't supposed to be read-only?

The field is not read-only, by default it is set to false then a user can update it to true once they have finished editing an article.

**Comment by MainaKamau92** [comment]
I noticed the `is_published` can be edited, is it by design?

**Comment by Raywire** [comment]
> I noticed the `is_published` can be edited, is it by design?

Yes, it is by design.

**Review by ipaullly — APPROVED** [review]
I like how you abstracted the code, for querying the database for an article by slug, into the `find_article()` function.

**Comment by Raywire** [comment]
> I like how you abstracted the code, for querying the database for an article by slug, into the `find_article()` function.

Thanks @ipaullly

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
