### PR TITLE
#164829373 create tags for articles

### PR DESCRIPTION
**Pull request by ipaullly**
#### Description
When a user creates an article, it is useful to have the option of tagging an article. tags allow users to access articles with similar themes, topics, or scopes. A user can also update tags for an article they have created. This feature enables users to search for articles with a particular tag or multiple tags 
#### Description of Task to be completed?
Tagging refers to the metadata that is assigned to a piece of content by the content creator and the readers/users of the content. Tagging allows for organization and or categorization of content.
#### How should this be manually tested?
- Retrieve all the branches and checkout to the branch housing the tag articles functionality 
```bash
git fetch --all
git checkout ft-tagging-articles-164829373
```
- set up a virtual environment with the following commands
```python
virtualenv venv
source venv/bin/activate
```
- Install dependencies
```python
pip install -r requirements.txt
```
- Run the server to begin accessing the URLs via POSTMAN
```python
python manage.py runserver
```

**Create article (POST: localhost/api/articles/)**
image
**Update article (PUT: localhost/api/articles/:slug/)**
image
**Search article(s) by tag(s) (GET: localhost/api/articles/?search=tag)**
image

#### What are the relevant pivotal tracker stories?
#164829373

### CODE REVIEW

**Comment by LarryKarani** [comment]
Good job the tags are created successfully.  My concern is when doing a tag search it searches the entire article and not the tags list.
for example, I searched the tag `the` it returned all the articles with the word `the` even though `the` does not exist in the tag list.

Screenshot 2019-04-23 at 21 57 03

Is this intentional? Kindly confirm before I approve

**Comment by ipaullly** [comment]
Thanks for pointing that out larry. I forgot to mention that I enabled the search functionality to search multiple tags at the same time so the server expects either:

image

or

image

The first search entry includes a search query with multiple tags in the input. when searching for a single tag, note that a single entry has to be followed by a comma.  
The reason for this is that I am taking in the inputs and making a list which I then compare against the tags field that contains tags contained in python lists

**Review by LarryKarani — DISMISSED** [review]
Thanks for the clarification on the tags searching issue. Everything works fine now.

**Review by Raywire — DISMISSED** [review]
The tag functionality works well, good job on taking the initiative to embed it into the search feature.

**Review by MainaKamau92 — APPROVED** [review]

**Review by Raywire — APPROVED** [review]
Good work.

**Pull request merged**
