### PR TITLE
#164829366 Comments Create, Read, Update and Delete

### PR DESCRIPTION
**Pull request by kihuha**
#### What does this PR do?
Configures the Create, Read Update and Delete endpoints for comments 

#### Description of the task to be completed
Have the following endpoints working

##### `POST` `localhost/api/articles/<slug:articles-slug>/comments/`
- Creates a comment for a particular article
```
{
	"comment": {
		"body": "Good article. Really enjoyed it"
	}
} 
```

##### `GET` `localhost/api/articles/<slug:articles-slug>/comments/`
- Retireve all the comments for a particular article

##### `GET` `localhost/api/articles/<slug:articles-slug>/comments/<int:ID>`
- Retrieve a particular comment

##### `PUT` `localhost/api/articles/<slug:articles-slug>/comments/<int:ID>`
- Updates a particular comment
```
{
	"comment": {
		"body": "Good article. Really enjoyed it - Updated"
	}
} 
```

##### `DELETE` `localhost/api/articles/<slug:articles-slug>/comments/<int:ID>`
- Deletes a particular comment

#### How should this be manually tested?
- Clone the repo and navigate to the root directory
- Create a virtual environment by typing `virtualenv venv` and activate it
- Install requirements by typing `pip install -r dev-requirements.txt`
- Setup a database and define the `DATABASE_URL` in a `.env` file. Export the configuration variable
- Run the tests by typing `python manage.py test`

#### Relevant PT stories
https://www.pivotaltracker.com/story/show/164829366

### CODE REVIEW

**Review by Raywire — COMMENTED** [review]
When I try to delete a nonexistent article the app crashes.
Screenshot 2019-04-09 at 12 16 15

**Comment by kihuha** [comment]
> When I try to delete a nonexistent article the app crashes.
> Screenshot 2019-04-09 at 12 16 15

Handled. Thanks for your feedback

**Review by Raywire — DISMISSED** [review]
The functionality works well.

**Review by LarryKarani — DISMISSED** [review]
Good job. Tested it locally the CRUD functionality works fine.

**Pull request closed without merging**
