### PR TITLE
Bg remove migrations files 165393022

### PR DESCRIPTION
**Pull request by LarryKarani**
__What does this PR do?__
 - Remove migration files to prevent unforeseen merge conflicts

__Description of tasks to be completed__

- Remove all migrations files from GitHub
- Add migrations scripts to travis.yml file
- Add migrations to .gitignore

__Pivotal tracker stories__
https://www.pivotaltracker.com/story/show/165393022

### CODE REVIEW

**Comment by WNjihia** [comment]
@larryTheGeek if I remember correctly, we also agreed we will remove the migrations folder from GitHub. This pr doesn't seem to be doing so. Do you mind looking into this?

**Comment by LarryKarani** [comment]
> @larryTheGeek if I remember correctly, we also agreed we will remove the migrations folder from GitHub. This pr doesn't seem to be doing so. Do you mind looking into this?

Let me look into it

**Comment by LarryKarani** [comment]
> @larryTheGeek if I remember correctly, we also agreed we will remove the migrations folder from GitHub. This pr doesn't seem to be doing so. Do you mind looking into this?

It won't work if I delete the migration folder containing the __init__.py file. All that was required was to remove the migration files but not the folder

**Review by WNjihia — APPROVED** [review]

**Review by Raywire — APPROVED** [review]
All traces of the migrations have been erased and the app still functions as expected, good job.

**Pull request merged**
