### PR TITLE
#164829371 Configure User Notifications

### PR DESCRIPTION
**Pull request by kihuha**
#### What does this PR do
Configures user notifications

#### Description of the task to be completed
- Sends notifications to users who follow a user when a user creates a new article
- Sends notification when a favourited article has new comments
- Send email notifications for the above-described notifications
- Allow users to subscribe and unsubscribe to email notifications

##### `GET` `localhost/api/notifications/`
- Retrieve all notifications
##### `GET` `localhost/api/notifications/<int:ID>`
- Retrieve a particular notification
##### `GET` `localhost/api/notifications/subscription`
- Check the status of your email notification subscription
##### `POST` `localhost/api/notifications/subscription`
- Subscribe or unsubscribe to email notifications
##### `GET` `localhost/api/notifications/<int:ID>/state`
- Check the state (is_read) of a notification
##### `PUT` `localhost/api/notifications/<int:ID>/state`
- Update the state (is_read) of a notification
##### `GET` `localhost/api/notifications/<int:action>`
action = 'read' | 'unread'
- Retrieves all the read/unread notifications
##### `GET` `localhost/api/notifications/read-all`
- Marks all notifications as 'read'

#### How should this be manually tested?
- Setup the following environmental variables in a .env file
```

DATABASE_URL=<database_url>
export DJANGO_SETTINGS_MODULE=authors.settings
export SECRET_KEY=<>
export FROM_EMAIL=<valid email>
export URL=<localhost>
export AH_HOST=<localhost>
export DOMAIN=<localhost>
```

- Clone the repo and navigate to the root directory
- Create a virtual environment by typing `virtualenv venv` and activate it
- Install requirements by typing `pip install -r dev-requirements.txt`
- Setup a database and define the `DATABASE_URL` in a `.env` file. Export the configuration variable
- Run the tests by typing `python manage.py test`

#### Relevant PT stories
https://www.pivotaltracker.com/story/show/164829371

### CODE REVIEW

**Review by LarryKarani — DISMISSED** [review]
Everything works fine I was able to get all the notifications. Good job

**Review by Kyppy — COMMENTED** [review]
I think you should include more docstrings in your code. While the views code may be short and easy to read, including docstrings would make your logic easier to follow. Especially because your feature logic is included inside other apps' views and so the logic is less apparent than if it was mostly in one file.

Also, some of your unit tests such as 'test_get_all_notifications' (lines 89-95) and 'test_get_notification' (lines 96-101) should be more comprehensive and test the actual output data. I feel that just testing the status code does not inform you if the actual data you receive is what you're expecting to get. It is easy for these tests to produce false positives.

**Comment by kihuha** [comment]
> I think you should include more docstrings in your code. While the views code may be short and easy to read, including docstrings would make your logic easier to follow. Especially because your feature logic is included inside other apps' views and so the logic is less apparent than if it was mostly in one file.
> 
> Also, some of your unit tests such as 'test_get_all_notifications' (lines 89-95) and 'test_get_notification' (lines 96-101) should be more comprehensive and test the actual output data. I feel that just testing the status code does not inform you if the actual data you receive is what you're expecting to get. It is easy for these tests to produce false positives.

Noted. I have implemented your feedback in the latest commit

**Comment by LarryKarani** [comment]
Is it possible to retrieve only the unread notifications?

**Comment by kihuha** [comment]
> Is it possible to retrieve only the unread notifications?

I have included this functionality. Please refer to the PR to view the endpoints

**Review by Kyppy — DISMISSED** [review]
The docstrings are clear and concise. The unit test output checks are more specific and useful in determining the efficacy of your methods.

**Review by kirega — DISMISSED** [review]

**Review by MainaKamau92 — APPROVED** [review]

**Review by Raywire — APPROVED** [review]

**Pull request merged**
