### PR TITLE
Chore(Update .gitignore):Update the .gitignore file

### PR DESCRIPTION
**Pull request by MainaKamau92**
#### What does this PR do?
Updates the .gitignore file 

#### Description
- Update the .gitignore file to exclude .vscode folder
- Update the .gitignore file to exclude Pipfile and Pipfile.lock files

#### PT Story
[#164829356]

### CODE REVIEW

**Review by Raywire — DISMISSED** [review]
Everything is in order.

**Review by kihuha — CHANGES_REQUESTED** [review]
You need to delete the original .vscode folder even though you have added it to the .gitignore

**Review by Raywire — DISMISSED** [review]
The conflict has been fixed and it's all good now.

**Comment by LarryKarani** [comment]
Everything is in order

**Review by LarryKarani — DISMISSED** [review]
Everything looks fine.

**Review by kihuha — DISMISSED** [review]

**Review by ipaullly — DISMISSED** [review]
Everything is ok, but why are we still ignoring Pipfile, and Pipfile.lock

**Review by Raywire — DISMISSED** [review]
Everything has been resolved, it looks good.

**Review by LarryKarani — DISMISSED** [review]
Looks fine

**Review by kihuha — DISMISSED** [review]
Looks good.

**Review by Kyppy — DISMISSED** [review]
The commit was atomic, which is good. Timely correction of conflict.

**Review by kihuha — APPROVED** [review]

**Review by Raywire — APPROVED** [review]
It looks alright.

**Pull request closed without merging**
