### PR TITLE
#164829355 Setup and Deploy to Heroku

### PR DESCRIPTION
**Pull request by kihuha**
#### What does this PR do?
Set's up Heroku for app hosting

#### Description of the task to be completed
Deploy the app to Heroku

#### Relevant PT stories
https://www.pivotaltracker.com/story/show/164829355

#### Screenshots
Screenshot 2019-03-28 at 10 33 37

### CODE REVIEW

**Review by MainaKamau92 — DISMISSED** [review]
Looks good, but there seems to be a conflict on `app.json`

**Review by Raywire — DISMISSED** [review]
Please resolve the conflict on app.json file by selecting the most recent updates that you have made pertaining to the configuration chosen for pipelining the app.

**Review by MainaKamau92 — DISMISSED** [review]

**Review by Raywire — DISMISSED** [review]
The issue seems resolved and everything looks good.

**Review by MainaKamau92 — APPROVED** [review]

**Review by Raywire — APPROVED** [review]
Everything is in order.

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
