### PR TITLE
#165284844 Fix Comment Update

### PR DESCRIPTION
**Pull request by kihuha**
#### What does this PR do?
Handles the `DoesNotExist` exception by displaying an informative error message

#### Relevant PT stories
https://www.pivotaltracker.com/story/show/165284844

### CODE REVIEW

**Review by Raywire — DISMISSED** [review]
Everything looks good but try to improve the coverage.

**Review by Raywire — APPROVED** [review]
Everything looks good.

**Comment by kirega** [comment]
Tests are all passing. Everything seems together.

**Review by kirega — APPROVED** [review]

**Comment by kihuha** [comment]
> Everything looks good but try to improve the coverage.

I added a test for checking that it fails when a user tries to update a non-existent comment

**Review by WNjihia — APPROVED** [review]

**Pull request merged**
